/**
 * Convert i18n/*.yaml (simple nested key: "value" maps) → static/i18n/*.json
 * No external deps — supports our constrained YAML subset.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'i18n');
const OUT = path.join(ROOT, 'static', 'i18n');
const LOCALES = ['en', 'mr', 'hi'];

function parseSimpleYaml(text) {
  const lines = text.replace(/\r\n/g, '\n').split('\n');
  const root = {};
  const stack = [{ indent: -1, obj: root }];

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    if (!raw.trim() || raw.trim().startsWith('#')) continue;

    const indent = raw.match(/^ */)[0].length;
    const trimmed = raw.trim();
    const colon = trimmed.indexOf(':');
    if (colon === -1) continue;

    const key = trimmed.slice(0, colon).trim();
    let valuePart = trimmed.slice(colon + 1).trim();

    while (stack.length > 1 && indent <= stack[stack.length - 1].indent) {
      stack.pop();
    }
    const parent = stack[stack.length - 1].obj;

    if (valuePart === '') {
      parent[key] = {};
      stack.push({ indent, obj: parent[key] });
      continue;
    }

    // Quoted string (supports escaped quotes)
    if (
      (valuePart.startsWith('"') && valuePart.endsWith('"')) ||
      (valuePart.startsWith("'") && valuePart.endsWith("'"))
    ) {
      const q = valuePart[0];
      let inner = valuePart.slice(1, -1);
      if (q === '"') {
        inner = inner
          .replace(/\\n/g, '\n')
          .replace(/\\"/g, '"')
          .replace(/\\\\/g, '\\');
      }
      parent[key] = inner;
    } else {
      parent[key] = valuePart;
    }
  }

  return root;
}

function main() {
  if (!fs.existsSync(OUT)) fs.mkdirSync(OUT, { recursive: true });

  const bundle = {};

  for (const locale of LOCALES) {
    const file = path.join(SRC, locale + '.yaml');
    if (!fs.existsSync(file)) {
      console.error('Missing:', file);
      process.exit(1);
    }
    const data = parseSimpleYaml(fs.readFileSync(file, 'utf8'));
    const outFile = path.join(OUT, locale + '.json');
    fs.writeFileSync(outFile, JSON.stringify(data, null, 2) + '\n', 'utf8');
    bundle[locale] = data;
    console.log('Wrote', path.relative(ROOT, outFile));
  }

  // Embedded bundle for file:// / offline reliability
  const dataJs = path.join(ROOT, 'static', 'js', 'i18n-data.js');
  const dir = path.dirname(dataJs);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(
    dataJs,
    '/* Auto-generated by scripts/build-i18n.js — do not edit by hand */\n' +
      'window.TZ_I18N_DATA = ' +
      JSON.stringify(bundle) +
      ';\n',
    'utf8'
  );
  console.log('Wrote', path.relative(ROOT, dataJs));
}

main();
